### ISSUE TITLE
Looks best from all but

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [afornalik/OX#3]
with only 2 PRs, one closed 2 hours ago there's not that big of a difference.

**Comment by LIttleAncientForestKami** [comment]
Why best of all: number of commits that you have on master branch. Commits should be small and incremental, so this bodes well. I'm troubled somewhat by the fact that you only had two merges so far and that you have 6 branches. That's a lot of branches for a project of that size. Also - 2 merges mean that either you had 8 branches or that some of your branches are getting stale. Either way you merge too rarely.

**Comment by afornalik** [comment]
Nice to hear that it's not so bad. I will merge more often, and I will stop creating so many branches. Thanks for opinion.
